# 1. Give the Application a Name
spring.application.name=SecureBank

# 2. Database Configuration (H2 In-Memory Database)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# 3. Enable the H2 Console (So we can see the tables in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 4. Hibernate Settings (Auto-create tables)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update